# docker-compose build
services:
  db:
    image: kartoza/postgis:13.0
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=ungr_m_n,mis_db
      - POSTGRES_USER=admin
      - POSTGRES_PASS=secret
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
  
  pgadmin:
    # image: dpage/pgadmin4:4.29
    image: dpage/pgadmin4:5.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: q@w.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8081:81"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  dbbackups:
    image: kartoza/pg-backup:13.0
    hostname: pg-backups
    volumes:
      - dbbackups:/backups
    environment:
      - DUMPPREFIX=PG_db
      - POSTGRES_USER=admin
      - POSTGRES_PASS=secret
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=ungr_m_n
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbbackups:
  postgis-data:
  pgadmin-data: